In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("cleaned_data.csv")

In [3]:
df.head()

,Unnamed: 0,loan_id,no_of_dependents,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,education_label,loan_status_label,self_employed_label
0,0,1,2,9600000,29900000,12,778,2400000,17600000,22700000,8000000,0,0,0
1,1,2,0,4100000,12200000,8,417,2700000,2200000,8800000,3300000,1,1,1
2,2,3,3,9100000,29700000,20,506,7100000,4500000,33300000,12800000,0,1,0
3,3,4,3,8200000,30700000,8,467,18200000,3300000,23300000,7900000,0,1,0
4,4,5,5,9800000,24200000,20,382,12400000,8200000,29400000,5000000,1,1,1

In [4]:
df.drop(['Unnamed: 0'], axis=1, inplace=True)

In [5]:
df.head()

,loan_id,no_of_dependents,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,education_label,loan_status_label,self_employed_label
0,1,2,9600000,29900000,12,778,2400000,17600000,22700000,8000000,0,0,0
1,2,0,4100000,12200000,8,417,2700000,2200000,8800000,3300000,1,1,1
2,3,3,9100000,29700000,20,506,7100000,4500000,33300000,12800000,0,1,0
3,4,3,8200000,30700000,8,467,18200000,3300000,23300000,7900000,0,1,0
4,5,5,9800000,24200000,20,382,12400000,8200000,29400000,5000000,1,1,1

# Splitting into dependent and independent

In [9]:
X = df[ ['no_of_dependents','income_annum','loan_amount','loan_term','cibil_score','residential_assets_value','commercial_assets_value','luxury_assets_value','bank_asset_value','education_label','self_employed_label']]
y = df['loan_status_label']

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
train_x, test_x, train_y, test_y = train_test_split(X,y, test_size=0.2)

In [13]:
len(train_x),len(train_y)

(3415, 3415)

In [14]:
len(test_x),len(test_y)

(854, 854)

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
model = LogisticRegression()

In [18]:
model.accuracy()

AttributeError: 'LogisticRegression' object has no attribute 'accuracy'